<a href="https://colab.research.google.com/github/surbhi-codehub/100-Days-SQL-Journey/blob/main/day02sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
run_sql("""SELECT department_name
FROM departments;""")

    department_name
0                HR
1           Finance
2                IT
3         Marketing
4             Sales
5        Operations
6           Support
7             Legal
8  Data Engineering
9          Security

In [8]:
run_sql("""SELECT Product_name, price
FROM products;""")

          product_name    price
0       Laptop Model 1  90499.0
1       Laptop Model 2  90999.0
2       Laptop Model 3  91499.0
3       Laptop Model 4  91999.0
4       Mobile Model 1  30499.0
5       Mobile Model 2  30999.0
6       Mobile Model 3  31499.0
7       Mobile Model 4  31999.0
8   Headphones Model 1   5499.0
9   Headphones Model 2   5999.0
10  Headphones Model 3   6499.0
11  Headphones Model 4   6999.0
12     Monitor Model 1  16499.0
13     Monitor Model 2  16999.0
14     Monitor Model 3  17499.0
15     Monitor Model 4  17999.0
16    Keyboard Model 1   2499.0
17    Keyboard Model 2   2999.0
18    Keyboard Model 3   3499.0
19    Keyboard Model 4   3999.0
20       Mouse Model 1   1499.0
21       Mouse Model 2   1999.0
22       Mouse Model 3   2499.0
23       Mouse Model 4   2999.0
24      Camera Model 1  46499.0

In [12]:
run_sql("""SELECT DISTINCT city
FROM customers;""")

        city
0  Bangalore
1     Mumbai
2    Chennai
3       Pune
4  Hyderabad
5      Delhi
6    Kolkata

In [15]:
run_sql("""SELECT DISTINCT job_title
FROM employees;""")

             job_title
0         HR Executive
1           Accountant
2    Software Engineer
3  Marketing Executive
4      Sales Executive
5   Operations Analyst
6     Support Engineer
7        Legal Advisor
8        Data Engineer
9     Security Analyst

In [16]:
run_sql("""SELECT first_name, last_name, email
FROM employees;""")

   first_name last_name                       email
0       Aarav     Patel    aarav.patel1@company.com
1      Vivaan     Patel   vivaan.patel2@company.com
2      Aditya       Das     aditya.das3@company.com
3        Riya       Das       riya.das4@company.com
4       Priya       Das      priya.das5@company.com
5        Neha    Taylor    neha.taylor6@company.com
6       Rahul       Roy      rahul.roy7@company.com
7        Amit       Roy       amit.roy8@company.com
8        John     Brown     john.brown9@company.com
9        Emma     Kumar    emma.kumar10@company.com
10       Noah     Singh    noah.singh11@company.com
11     Olivia       Roy    olivia.roy12@company.com
12       Liam     Singh    liam.singh13@company.com
13     Sophia       Roy    sophia.roy14@company.com
14     Ananya     Singh  ananya.singh15@company.com
15      Karan    Taylor  karan.taylor16@company.com
16      Rohan     Singh   rohan.singh17@company.com
17      Sneha    Sharma  sneha.sharma18@company.com
18      David     Singh   david.singh19@company.com
19       Sara    Taylor   sara.taylor20@company.com
20      Arjun    Taylor  arjun.taylor21@company.com
21       Isha       Roy      isha.roy22@company.com
22      Kabir    Sharma  kabir.sharma23@company.com
23      Meera     Singh   meera.singh24@company.com
24     Vikram       Roy    vikram.roy25@company.com
25      Nisha    Sharma  nisha.sharma26@company.com
26     Daniel       Roy    daniel.roy27@company.com
27      Grace     Brown   grace.brown28@company.com
28      Aryan       Das     aryan.das29@company.com
29      Pooja    Sharma  pooja.sharma30@company.com