<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day014sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
#1 Display all products taht are NOT in the 'Electronic' category.
run_sql("""SELECT *
FROM products
WHERE NOT category = 'Electronic';""")

    product_id        product_name    category    price  stock_quantity
0            1      Laptop Model 1      Laptop  90499.0              35
1            2      Laptop Model 2      Laptop  90999.0               0
2            3      Laptop Model 3      Laptop  91499.0              50
3            4      Laptop Model 4      Laptop  91999.0               5
4            5      Mobile Model 1      Mobile  30499.0              35
5            6      Mobile Model 2      Mobile  30999.0               0
6            7      Mobile Model 3      Mobile  31499.0              12
7            8      Mobile Model 4      Mobile  31999.0               0
8            9  Headphones Model 1  Headphones   5499.0              80
9           10  Headphones Model 2  Headphones   5999.0               0
10          11  Headphones Model 3  Headphones   6499.0              80
11          12  Headphones Model 4  Headphones   6999.0               5
12          13     Monitor Model 1     Monitor  16499.0              20
13          14     Monitor Model 2     Monitor  16999.0               0
14          15     Monitor Model 3     Monitor  17499.0               5
15          16     Monitor Model 4     Monitor  17999.0              20
16          17    Keyboard Model 1    Keyboard   2499.0              80
17          18    Keyboard Model 2    Keyboard   2999.0              35
18          19    Keyboard Model 3    Keyboard   3499.0               5
19          20    Keyboard Model 4    Keyboard   3999.0              50
20          21       Mouse Model 1       Mouse   1499.0               0
21          22       Mouse Model 2       Mouse   1999.0              20
22          23       Mouse Model 3       Mouse   2499.0              35
23          24       Mouse Model 4       Mouse   2999.0               0
24          25      Camera Model 1      Camera  46499.0               0

In [3]:
#2 Display customer who are NOT from 'Bangalore'.
run_sql("""SELECT *
FROM customers
WHERE NOT city = 'Bangalore';""")

    customer_id first_name last_name              email       phone       city
0             3      Mohit     Kumar    mohit3@mail.com  9208428912     Mumbai
1             4     Simran       Das   simran4@mail.com  9979444461    Chennai
2             5       Yash    Sharma     yash5@mail.com  9426111115       Pune
3             6     Anjali     Singh   anjali6@mail.com  9693986973       Pune
4             7     Deepak    Wilson   deepak7@mail.com  9906274295  Hyderabad
5             8      Komal       Roy    komal8@mail.com  9467566361      Delhi
6             9      Nitin     Brown    nitin9@mail.com  9899533704  Hyderabad
7            10      Aisha     Kumar   aisha10@mail.com  9332083015    Chennai
8            12       Ritu     Kumar    ritu12@mail.com  9658448295      Delhi
9            13      Mohit       Das   mohit13@mail.com  9361812679  Hyderabad
10           14     Simran    Taylor  simran14@mail.com  9604314504    Kolkata
11           15       Yash    Sharma    yash15@mail.com  9702952921  Hyderabad
12           17     Deepak    Taylor  deepak17@mail.com  9865412201  Hyderabad
13           18      Komal     Singh   komal18@mail.com  9504584808    Kolkata
14           19      Nitin    Taylor   nitin19@mail.com  9995653703  Hyderabad
15           20      Aisha     Kumar   aisha20@mail.com  9659589923      Delhi
16           21      Akash    Sharma   akash21@mail.com  9124393190       Pune
17           22       Ritu     Kumar    ritu22@mail.com  9882449902  Hyderabad
18           23      Mohit    Taylor   mohit23@mail.com  9744597750    Kolkata
19           24     Simran       Das  simran24@mail.com  9185583902       Pune
20           25       Yash     Singh    yash25@mail.com  9834197053       Pune
21           26     Anjali     Kumar  anjali26@mail.com  9988357959      Delhi
22           27     Deepak    Sharma  deepak27@mail.com  9922832851      Delhi
23           28      Komal     Singh   komal28@mail.com  9110051432     Mumbai
24           29      Nitin    Wilson   nitin29@mail.com  9200774016  Hyderabad
25           30      Aisha       Das   aisha30@mail.com  9627755893     Mumbai
26           31      Akash     Gupta   akash31@mail.com  9750806415    Kolkata
27           32       Ritu    Sharma    ritu32@mail.com  9787498671    Chennai
28           33      Mohit       Roy   mohit33@mail.com  9665152033      Delhi
29           34     Simran    Wilson  simran34@mail.com  9642604350       Pune
30           35       Yash       Das    yash35@mail.com  9847568100  Hyderabad
31           36     Anjali     Gupta  anjali36@mail.com  9310837702    Chennai
32           37     Deepak    Wilson  deepak37@mail.com  9413891625       Pune
33           38      Komal       Roy   komal38@mail.com  9634822466    Chennai
34           39      Nitin       Das   nitin39@mail.com  9759424149    Chennai
35           40      Aisha    Taylor   aisha40@mail.com  9829603810    Kolkata

In [4]:
# 3 Display employees whose department_id is NOT 1.
run_sql("""SELECT *
FROM employees
WHERE NOT department_id = 1;""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,2,Vivaan,Patel,2,2022-01-10,105000.0,Accountant,Bangalore,vivaan.patel2@company.com
1,3,Aditya,Das,3,2021-11-02,45000.0,Software Engineer,Delhi,aditya.das3@company.com
2,4,Riya,Das,4,2024-02-16,117500.0,Marketing Executive,Delhi,riya.das4@company.com
3,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com
4,6,Neha,Taylor,6,2024-11-24,67500.0,Operations Analyst,Hyderabad,neha.taylor6@company.com
5,7,Rahul,Roy,7,2019-02-23,90000.0,Support Engineer,Mumbai,rahul.roy7@company.com
6,8,Amit,Roy,8,2021-05-07,105000.0,Legal Advisor,Bangalore,amit.roy8@company.com
7,9,John,Brown,9,2021-11-22,45000.0,Data Engineer,Pune,john.brown9@company.com
8,10,Emma,Kumar,10,2023-07-25,97500.0,Security Analyst,Kolkata,emma.kumar10@company.com
9,12,Olivia,Roy,2,2021-02-05,50000.0,Accountant,Bangalore,olivia.roy12@company.com
10,13,Liam,Singh,3,2020-10-03,105000.0,Software Engineer,Mumbai,liam.singh13@company.com
11,14,Sophia,Roy,4,2022-01-01,97500.0,Marketing Executive,Delhi,sophia.roy14@company.com
12,15,Ananya,Singh,5,2022-08-02,72500.0,Sales Executive,Kolkata,ananya.singh15@company.com
13,16,Karan,Taylor,6,2021-01-27,117500.0,Operations Analyst,Pune,karan.taylor16@company.com
14,17,Rohan,Singh,7,2022-04-21,52500.0,Support Engineer,Mumbai,rohan.singh17@company.com
15,18,Sneha,Sharma,8,2020-01-20,50000.0,Legal Advisor,Bangalore,sneha.sharma18@company.com
16,19,David,Singh,9,2021-04-21,62500.0,Data Engineer,Pune,david.singh19@company.com
17,20,Sara,Taylor,10,2023-12-21,85000.0,Security Analyst,Delhi,sara.taylor20@company.com
18,22,Isha,Roy,2,2022-08-14,60000.0,Accountant,Hyderabad,isha.roy22@company.com
19,23,Kabir,Sharma,3,2023-05-02,105000.0,Software Engineer,Mumbai,kabir.sharma23@company.com
20,24,Meera,Singh,4,2021-07-03,112500.0,Marketing Executive,Hyderabad,meera.singh24@company.com
21,25,Vikram,Roy,5,2024-11-20,57500.0,Sales Executive,Pune,vikram.roy25@company.com
22,26,Nisha,Sharma,6,2023-08-06,110000.0,Operations Analyst,Pune,nisha.sharma26@company.com
23,27,Daniel,Roy,7,2023-05-29,60000.0,Support Engineer,Pune,daniel.roy27@company.com
24,28,Grace,Brown,8,2023-03-29,40000.0,Legal Advisor,Bangalore,grace.brown28@company.com
25,29,Aryan,Das,9,2022-12-19,70000.0,Data Engineer,Hyderabad,aryan.das29@company.com
26,30,Pooja,Sharma,10,2020-05-02,120000.0,Security Analyst,Pune,pooja.sharma30@company.com

In [5]:
#4 Display orders that were NOT placed by customer_id 1.
run_sql("""SELECT *
FROM orders
WHERE NOT customer_id = 1;""")

    order_id  customer_id  product_id  order_date  quantity
0          1           20           2  2025-10-15         4
1          2           11          16  2025-02-26         2
2          3           29          24  2024-01-15         3
3          4           17          23  2024-09-08         5
4          5           16           3  2024-12-14         1
..       ...          ...         ...         ...       ...
94        96           24           8  2026-03-28         5
95        97           32          11  2024-10-06         2
96        98           35           8  2025-02-24         2
97        99            4          23  2024-09-19         1
98       100           32          17  2024-07-13         5

[99 rows x 5 columns]

In [7]:
#5 Display employee_id ,first_name, and last_name for employees whose department_id is NOT 2.
run_sql("""SELECT employee_id, first_name, last_name
FROM employees
WHERE NOT department_id = 2;""")

    employee_id first_name last_name
0             1      Aarav     Patel
1             3     Aditya       Das
2             4       Riya       Das
3             5      Priya       Das
4             6       Neha    Taylor
5             7      Rahul       Roy
6             8       Amit       Roy
7             9       John     Brown
8            10       Emma     Kumar
9            11       Noah     Singh
10           13       Liam     Singh
11           14     Sophia       Roy
12           15     Ananya     Singh
13           16      Karan    Taylor
14           17      Rohan     Singh
15           18      Sneha    Sharma
16           19      David     Singh
17           20       Sara    Taylor
18           21      Arjun    Taylor
19           23      Kabir    Sharma
20           24      Meera     Singh
21           25     Vikram       Roy
22           26      Nisha    Sharma
23           27     Daniel       Roy
24           28      Grace     Brown
25           29      Aryan       Das
26           30      Pooja    Sharma

In [9]:
# Bonus Challenge
# Choose any table and write a query that excludes one specific value using NOT.
run_sql("""SELECT *
FROM customers
WHERE NOT city = 'Delhi';""")

    customer_id first_name last_name              email       phone       city
0             1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
1             2       Ritu       Das     ritu2@mail.com  9627404182  Bangalore
2             3      Mohit     Kumar    mohit3@mail.com  9208428912     Mumbai
3             4     Simran       Das   simran4@mail.com  9979444461    Chennai
4             5       Yash    Sharma     yash5@mail.com  9426111115       Pune
5             6     Anjali     Singh   anjali6@mail.com  9693986973       Pune
6             7     Deepak    Wilson   deepak7@mail.com  9906274295  Hyderabad
7             9      Nitin     Brown    nitin9@mail.com  9899533704  Hyderabad
8            10      Aisha     Kumar   aisha10@mail.com  9332083015    Chennai
9            11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
10           13      Mohit       Das   mohit13@mail.com  9361812679  Hyderabad
11           14     Simran    Taylor  simran14@mail.com  9604314504    Kolkata
12           15       Yash    Sharma    yash15@mail.com  9702952921  Hyderabad
13           16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore
14           17     Deepak    Taylor  deepak17@mail.com  9865412201  Hyderabad
15           18      Komal     Singh   komal18@mail.com  9504584808    Kolkata
16           19      Nitin    Taylor   nitin19@mail.com  9995653703  Hyderabad
17           21      Akash    Sharma   akash21@mail.com  9124393190       Pune
18           22       Ritu     Kumar    ritu22@mail.com  9882449902  Hyderabad
19           23      Mohit    Taylor   mohit23@mail.com  9744597750    Kolkata
20           24     Simran       Das  simran24@mail.com  9185583902       Pune
21           25       Yash     Singh    yash25@mail.com  9834197053       Pune
22           28      Komal     Singh   komal28@mail.com  9110051432     Mumbai
23           29      Nitin    Wilson   nitin29@mail.com  9200774016  Hyderabad
24           30      Aisha       Das   aisha30@mail.com  9627755893     Mumbai
25           31      Akash     Gupta   akash31@mail.com  9750806415    Kolkata
26           32       Ritu    Sharma    ritu32@mail.com  9787498671    Chennai
27           34     Simran    Wilson  simran34@mail.com  9642604350       Pune
28           35       Yash       Das    yash35@mail.com  9847568100  Hyderabad
29           36     Anjali     Gupta  anjali36@mail.com  9310837702    Chennai
30           37     Deepak    Wilson  deepak37@mail.com  9413891625       Pune
31           38      Komal       Roy   komal38@mail.com  9634822466    Chennai
32           39      Nitin       Das   nitin39@mail.com  9759424149    Chennai
33           40      Aisha    Taylor   aisha40@mail.com  9829603810    Kolkata