<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day016sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# Topic: Using BETWEEN to filter a range of values.

In [3]:
#1 Display products whose price is BETWEEN 1000 AND 5000.
run_sql("""SELECT *
FROM products
WHERE price BETWEEN 1000 AND 5000;""")

   product_id      product_name  category   price  stock_quantity
0          17  Keyboard Model 1  Keyboard  2499.0              80
1          18  Keyboard Model 2  Keyboard  2999.0              35
2          19  Keyboard Model 3  Keyboard  3499.0               5
3          20  Keyboard Model 4  Keyboard  3999.0              50
4          21     Mouse Model 1     Mouse  1499.0               0
5          22     Mouse Model 2     Mouse  1999.0              20
6          23     Mouse Model 3     Mouse  2499.0              35
7          24     Mouse Model 4     Mouse  2999.0               0

In [4]:
#2 Display employees whose employee_id is Between 3 AND 8.
run_sql("""SELECT *
FROM employees
WHERE employee_id BETWEEN 3 AND 8;""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,3,Aditya,Das,3,2021-11-02,45000.0,Software Engineer,Delhi,aditya.das3@company.com
1,4,Riya,Das,4,2024-02-16,117500.0,Marketing Executive,Delhi,riya.das4@company.com
2,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com
3,6,Neha,Taylor,6,2024-11-24,67500.0,Operations Analyst,Hyderabad,neha.taylor6@company.com
4,7,Rahul,Roy,7,2019-02-23,90000.0,Support Engineer,Mumbai,rahul.roy7@company.com
5,8,Amit,Roy,8,2021-05-07,105000.0,Legal Advisor,Bangalore,amit.roy8@company.com

In [12]:
#3 Display customers whose customer_id is BETWEEN 2 AND 6.
run_sql("""SELECT *
FROM customers
WHERE customer_id BETWEEN 2 AND 6;""")

   customer_id first_name last_name             email       phone       city
0            2       Ritu       Das    ritu2@mail.com  9627404182  Bangalore
1            3      Mohit     Kumar   mohit3@mail.com  9208428912     Mumbai
2            4     Simran       Das  simran4@mail.com  9979444461    Chennai
3            5       Yash    Sharma    yash5@mail.com  9426111115       Pune
4            6     Anjali     Singh  anjali6@mail.com  9693986973       Pune

In [8]:
#4 Display orders whose order_id is BETWEEN 5 AND 15.
run_sql("""SELECT *
FROM orders
WHERE order_id BETWEEN 5 AND 15;""")

    order_id  customer_id  product_id  order_date  quantity
0          5           16           3  2024-12-14         1
1          6           15          20  2025-09-01         2
2          7            2          20  2024-05-15         2
3          8           13          19  2026-03-11         1
4          9           28           7  2025-01-10         1
5         10            1          10  2024-07-16         5
6         11           13          14  2024-12-19         2
7         12           26          16  2025-12-07         1
8         13           14          17  2026-04-14         5
9         14           33          19  2024-01-19         1
10        15           27           2  2024-10-16         2

In [9]:
#5 Display employee_id, first_name, and last_name for employees whose department_id is 2 and employee_id is BETWEEN 2 AND 10.
run_sql("""SELECT employee_id, first_name, last_name
FROM employees
WHERE department_id = 2
AND employee_id BETWEEN 2 AND 10;""")

   employee_id first_name last_name
0            2     Vivaan     Patel

In [10]:
# Bonus Challenge
# Any numeric column in the database and retrive rows within a range using BETWEEN.
run_sql("""SELECT *
FROM products
WHERE product_id BETWEEN 10 AND 20;""")

    product_id        product_name    category    price  stock_quantity
0           10  Headphones Model 2  Headphones   5999.0               0
1           11  Headphones Model 3  Headphones   6499.0              80
2           12  Headphones Model 4  Headphones   6999.0               5
3           13     Monitor Model 1     Monitor  16499.0              20
4           14     Monitor Model 2     Monitor  16999.0               0
5           15     Monitor Model 3     Monitor  17499.0               5
6           16     Monitor Model 4     Monitor  17999.0              20
7           17    Keyboard Model 1    Keyboard   2499.0              80
8           18    Keyboard Model 2    Keyboard   2999.0              35
9           19    Keyboard Model 3    Keyboard   3499.0               5
10          20    Keyboard Model 4    Keyboard   3999.0              50